# Use these exact values
chain_id = "namada.5f5de2dd1b88cba30586420"
indexer_url = "https://indexer.namada.tududes.com"
rpc_url = "https://rpc.namada.tududes.com"
masp_indexer_url = "https://masp-indexer.namada.tududes.com"
